import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import QueryWrapper from "@/components/providers/provider-client";

import "@/styles/globals.css";

import { Toaster } from "@/components/ui/toaster";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Facebook clone",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  keywords: ["Next.js", "React", "Tailwind CSS", "Clone app"],
  authors: [
    {
      name: "iori",
      url: "https://github.com/iorise",
    },
  ],
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <QueryWrapper>
        <html lang="en" suppressHydrationWarning>
          <body className={font.className}>
            {children}
            <Toaster />
          </body>
        </html>
      </QueryWrapper>
    </ClerkProvider>
  );
}
