import React from "react";

import { Metadata } from "next";

import { SidebarSearch } from "@/components/sidebar-search";

export const metadata: Metadata = {
  title: "Facebook clone",
  description: "Generated by create next app",
};

interface SearchLayoutProps {
  children: React.ReactNode;
}
export default function SearchLayout({ children }: SearchLayoutProps) {
  return (
    <div className="flex">
      <aside>
        <SidebarSearch />
      </aside>
      {children}
    </div>
  );
}
